CONTIKI_PROJECT = udp-client overload-client udp-server
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += metrics.c
PROJECT_SOURCEFILES += utils.c

CONTIKI = ../contiki-ng
include $(CONTIKI)/Makefile.include
