#pragma once

#define LOG_CONF_LEVEL_RPL LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_WARN

#define RPL_CONF_OF_OCP RPL_OF

#define TSCH_LOG_CONF_PER_SLOT 0
#define QUEUEBUF_CONF_STATS 0
#define LINK_STATS_CONF_PACKET_COUNTERS 1
