#pragma once

#define RPL_CONF_OF_OCP RPL_OF

#define LOG_CONF_LEVEL_RPL LOG_LEVEL_INFO

#define RPL_CONF_MULTIPLE_METRICS 1

#define TSCH_LOG_CONF_PER_SLOT 0
#define QUEUEBUF_CONF_STATS 0
#define LINK_STATS_CONF_PACKET_COUNTERS 1
