#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define ENERGEST_CONF_ON 1

/*
#if BUILD_CLIENT
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_DBG
#endif
*/

#ifdef CONTIKI_TARGET_SKY
/* Save some RAM and ROM */

#ifndef QUEUEBUF_CONF_NUM
#define QUEUEBUF_CONF_NUM 8
#endif /* QUEUEBUF_CONF_NUM */

#define UIP_CONF_BUFFER_SIZE 140
#define BORDER_ROUTER_CONF_WEBSERVER 0
#endif /* CONTIKI_TARGET_SKY */

#endif /* PROJECT_CONF_H_ */
