#!/usr/bin/env python3
"""
Convert a trained LightGBM PDR model (see models.train) into portable,
float-free, fixed-point C code, for eventual embedding into the mote
firmware's "mlof" RPL objective function
(rpl/contiki-ng/os/net/routing/rpl-lite/rpl-mlof.c).

This only emits a standalone predictor .c/.h pair — it does NOT touch
rpl-mlof.c's best_parent() TODOs; wiring the generated predictor in there is
separate, later work.

Why fixed-point: the mote firmware uses no `float` anywhere (ETX is a
uint16_t fixed-point value, see LINK_STATS_ETX_DIVISOR in
rpl/contiki-ng/os/net/link-stats.h) and this follows that convention rather
than introducing float. Each feature's real-world (training-time) value maps
to a fixed-point integer via FEATURE_SCALES below:
  - etx: on-mote, nbr_link_metric()/nbr->mlof.etx are already
    ETX * LINK_STATS_ETX_DIVISOR (128) -- the model is trained on the real
    (unscaled) ETX value logged by rpl/motes/client/metrics.c, so thresholds
    are scaled back up by the same divisor to compare directly against that
    raw on-mote value.
  - hop_count, ppm, cpu_util, num_neighbours are already plain integers
    on-mote (e.g. cpu_util 0..100 from rpl-mlof.c's cpu_usage_percent()), so
    they need no scaling (scale 1).
The predicted PDR is returned the same way: an integer 0..PDR_DIVISOR
representing 0%..100%, rather than a float 0..1.

Usage as CLI:
    python models/to_c.py --model pdr_model.txt --out-dir generated

Usage as module:
    from models.to_c import convert_to_c
    convert_to_c("pdr_model.txt", "generated")
"""

from __future__ import annotations

import argparse
import math
import shutil
import subprocess
import tempfile
from pathlib import Path

import lightgbm as lgb
import numpy as np

FEATURE_SCALES = {
    "etx": 128,  # LINK_STATS_ETX_DIVISOR
    "hop_count": 1,
    "ppm": 1,
    "cpu_util": 1,
    "num_neighbours": 1,
}

# predict_pdr() returns an integer 0..PDR_DIVISOR representing 0%..100% PDR
# (the same "scaled integer" idea as ETX_DIVISOR, just for the model output).
PDR_DIVISOR = 10000


def _feature_of(node: dict, feature_names: list[str]) -> str:
    name = feature_names[node["split_feature"]]
    if name not in FEATURE_SCALES:
        raise KeyError(
            f"No fixed-point scale configured for feature {name!r} in FEATURE_SCALES"
        )
    return name


def _render_node(node: dict, feature_names: list[str]) -> str:
    """Render one LightGBM tree node (and its subtree) as a C statement."""
    if "leaf_value" in node:
        scaled = round(node["leaf_value"] * PDR_DIVISOR)
        return f"return {scaled};"

    if node["decision_type"] != "<=":
        raise ValueError(
            f"Unsupported split type {node['decision_type']!r} -- only numerical "
            "'<=' splits are supported (no categorical features)."
        )

    feature = _feature_of(node, feature_names)
    scale = FEATURE_SCALES[feature]
    threshold = math.floor(node["threshold"] * scale)

    left = _render_node(node["left_child"], feature_names)
    right = _render_node(node["right_child"], feature_names)
    return f"if ({feature} <= {threshold}) {{ {left} }} else {{ {right} }}"


def _tree_function(index: int, tree_structure: dict, feature_names: list[str], params: str) -> str:
    body = _render_node(tree_structure, feature_names)
    return f"static int32_t tree_{index}({params}) {{\n  {body}\n}}\n"


def _params_decl(feature_names: list[str]) -> str:
    return ", ".join(f"uint16_t {name}" for name in feature_names)


def _args_list(feature_names: list[str]) -> str:
    return ", ".join(feature_names)


def generate_c_source(dump: dict, func_name: str) -> tuple[str, str]:
    """Build the .c and .h file contents from a booster's dump_model() dict."""
    feature_names = dump["feature_names"]
    unknown = set(feature_names) - set(FEATURE_SCALES)
    if unknown:
        raise KeyError(f"No fixed-point scale configured for feature(s): {sorted(unknown)}")

    params = _params_decl(feature_names)
    args = _args_list(feature_names)
    n_trees = len(dump["tree_info"])

    tree_fns = "\n".join(
        _tree_function(i, tree["tree_structure"], feature_names, params)
        for i, tree in enumerate(dump["tree_info"])
    )
    tree_calls = "\n".join(f"  acc += tree_{i}({args});" for i in range(n_trees))

    header_guard = f"{func_name.upper()}_H_"
    header = f"""\
/* Auto-generated by scripts/models/to_c.py from a trained LightGBM model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#ifndef {header_guard}
#define {header_guard}

#include <stdint.h>

/* {func_name}() returns an integer 0..{func_name.upper()}_DIVISOR representing
 * 0%..100% predicted PDR (fixed-point, no float -- see module docstring in
 * scripts/models/to_c.py for what scale each argument is expected in). */
#define {func_name.upper()}_DIVISOR {PDR_DIVISOR}

uint16_t {func_name}({params});

#endif /* {header_guard} */
"""

    source = f"""\
/* Auto-generated by scripts/models/to_c.py from a trained LightGBM model
 * ({n_trees} trees). DO NOT EDIT BY HAND -- retrain and re-run the
 * converter instead. */
#include "{func_name}.h"

{tree_fns}
uint16_t {func_name}({params}) {{
  int32_t acc = 0;
{tree_calls}
  if (acc < 0) {{
    acc = 0;
  }} else if (acc > {func_name.upper()}_DIVISOR) {{
    acc = {func_name.upper()}_DIVISOR;
  }}
  return (uint16_t)acc;
}}
"""
    return source, header


def convert_to_c(
    model_path: str | Path, out_dir: str | Path, func_name: str = "mlof_predict_pdr"
) -> tuple[Path, Path]:
    """Load a trained LightGBM model and write <func_name>.c/.h under out_dir."""
    booster = lgb.Booster(model_file=str(model_path))
    dump = booster.dump_model()
    source, header = generate_c_source(dump, func_name)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    c_path = out_dir / f"{func_name}.c"
    h_path = out_dir / f"{func_name}.h"
    c_path.write_text(source)
    h_path.write_text(header)
    return c_path, h_path


def _reference_predict(dump: dict, feature_ints: dict[str, int]) -> int:
    """Pure-Python simulation of the exact fixed-point logic generate_c_source()
    emits (same threshold flooring, same per-leaf rounding) -- used to verify
    the generated C without needing a compiler.
    """
    feature_names = dump["feature_names"]

    def walk(node: dict) -> int:
        if "leaf_value" in node:
            return round(node["leaf_value"] * PDR_DIVISOR)
        feature = _feature_of(node, feature_names)
        scale = FEATURE_SCALES[feature]
        threshold = math.floor(node["threshold"] * scale)
        branch = node["left_child"] if feature_ints[feature] <= threshold else node["right_child"]
        return walk(branch)

    acc = sum(walk(tree["tree_structure"]) for tree in dump["tree_info"])
    return max(0, min(PDR_DIVISOR, acc))


def verify(model_path: str | Path, out_dir: str | Path, func_name: str, n_samples: int = 50) -> None:
    """Sanity-check the generated C against the trained model on random samples:
    1. Compares the pure-Python fixed-point reference against the real
       (float) model, to report the quantization error fixed-point rounding
       introduces.
    2. If a C compiler is available, actually compiles and runs the
       generated C and confirms it EXACTLY matches the Python reference (a
       mismatch here would mean a bug in the C code generation itself).
    """
    booster = lgb.Booster(model_file=str(model_path))
    dump = booster.dump_model()
    feature_names = dump["feature_names"]

    rng = np.random.default_rng(0)
    sample_ranges = {
        "etx": (1.0, 4.0),
        "hop_count": (0, 8),
        "ppm": (10, 60),
        "cpu_util": (0, 100),
        "num_neighbours": (0, 20),
    }

    max_error = 0
    rows = []
    for _ in range(n_samples):
        real_row = {f: rng.uniform(*sample_ranges[f]) for f in feature_names}
        feature_ints = {
            f: int(round(real_row[f] * FEATURE_SCALES[f])) for f in feature_names
        }
        real_row_for_model = {f: feature_ints[f] / FEATURE_SCALES[f] for f in feature_names}
        expected = booster.predict([[real_row_for_model[f] for f in feature_names]])[0]
        expected_scaled = max(0, min(PDR_DIVISOR, round(expected * PDR_DIVISOR)))
        actual = _reference_predict(dump, feature_ints)
        max_error = max(max_error, abs(actual - expected_scaled))
        rows.append((feature_ints, actual))

    print(
        f"Python fixed-point reference vs. real model: max error "
        f"{max_error} / {PDR_DIVISOR} ({max_error / PDR_DIVISOR * 100:.2f} pp) over {n_samples} samples"
    )

    cc = shutil.which("cc") or shutil.which("gcc")
    if cc is None:
        print("No C compiler found -- skipping compiled-C cross-check.")
        return

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        c_path, h_path = convert_to_c(model_path, tmp_path, func_name)
        args_decl = ", ".join(feature_names)
        harness = tmp_path / "harness.c"
        harness.write_text(
            f"""\
#include <stdio.h>
#include <stdlib.h>
#include "{h_path.name}"
int main(int argc, char **argv) {{
  (void)argc;
  uint16_t {args_decl};
{"".join(f"  {f} = (uint16_t)atoi(argv[{i + 1}]);\n" for i, f in enumerate(feature_names))}
  printf("%u\\n", {func_name}({", ".join(feature_names)}));
  return 0;
}}
"""
        )
        binary = tmp_path / "harness"
        result = subprocess.run(
            [cc, "-std=c99", "-O1", str(c_path), str(harness), "-o", str(binary)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print("Compiled-C cross-check FAILED to build:\n" + result.stderr)
            return

        mismatches = 0
        for feature_ints, expected in rows:
            args = [str(feature_ints[f]) for f in feature_names]
            out = subprocess.run([str(binary), *args], capture_output=True, text=True)
            actual = int(out.stdout.strip())
            if actual != expected:
                mismatches += 1
        if mismatches:
            print(f"Compiled-C cross-check: {mismatches}/{n_samples} MISMATCHES vs. Python reference!")
        else:
            print(f"Compiled-C cross-check: all {n_samples} samples match the Python reference exactly.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert a trained LightGBM PDR model to fixed-point C."
    )
    parser.add_argument("--model", type=str, required=True, help="Path to a saved LightGBM model")
    parser.add_argument("--out-dir", type=str, default="generated", help="Output directory for the .c/.h")
    parser.add_argument("--func-name", type=str, default="mlof_predict_pdr")
    parser.add_argument("--samples", type=int, default=50, help="Number of random samples to verify with")
    parser.add_argument("--skip-verify", action="store_true")

    args = parser.parse_args()
    c_path, h_path = convert_to_c(args.model, args.out_dir, args.func_name)
    print(f"Wrote {c_path}\nWrote {h_path}")

    if not args.skip_verify:
        verify(args.model, args.out_dir, args.func_name, args.samples)
