from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

import lightgbm as lgb
import m2cgen


def convert_to_c(
    model_path: str | Path, out_dir: str | Path, func_name: str = "mlof_predict_pdr"
) -> tuple[Path, Path]:
    booster = lgb.Booster(model_file=str(model_path))
    feature_names = booster.feature_name()

    model = lgb.LGBMRegressor()
    model._Booster = booster
    model.fitted_ = True
    source_body = m2cgen.export_to_c(model, function_name=func_name)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    c_path = out_dir / f"{func_name}.c"
    h_path = out_dir / f"{func_name}.h"

    header_guard = f"{func_name.upper()}_H_"
    header = f"""\
/* Auto-generated by scripts/models/to_c.py (via m2cgen) from a trained
 * LightGBM model. DO NOT EDIT BY HAND -- retrain and re-run the converter
 * instead.
 *
 * input[] must hold these features, in this order:
 *   {", ".join(f"{i}: {name}" for i, name in enumerate(feature_names))}
 */
#ifndef {header_guard}
#define {header_guard}

double {func_name}(double *input);

#endif /* {header_guard} */
"""
    source = (
        "/* Auto-generated by scripts/models/to_c.py (via m2cgen) from a "
        "trained LightGBM model.\n"
        " * DO NOT EDIT BY HAND -- retrain and re-run the converter "
        "instead. */\n"
        f'#include "{func_name}.h"\n\n' + source_body
    )

    c_path.write_text(source)
    h_path.write_text(header)
    return c_path, h_path


def measure_size(c_path: str | Path, mcu: str = "msp430f2617") -> str | None:
    gcc = shutil.which("msp430-gcc")
    size_tool = shutil.which("msp430-size")
    if gcc is None or size_tool is None:
        print("msp430-gcc/msp430-size not found -- skipping size measurement.")
        return None

    c_path = Path(c_path)
    with tempfile.TemporaryDirectory() as tmp:
        o_path = Path(tmp) / (c_path.stem + ".o")
        result = subprocess.run(
            [
                gcc,
                f"-mmcu={mcu}",
                "-Os",
                "-I",
                str(c_path.parent),
                "-c",
                str(c_path),
                "-o",
                str(o_path),
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print("msp430-gcc FAILED to compile:\n" + result.stderr)
            return None

        size_result = subprocess.run(
            [size_tool, str(o_path)], capture_output=True, text=True
        )
        print(size_result.stdout)
        return size_result.stdout
